[package]
name = "ethnum-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[features]
intrinsics = ["ethnum/intrinsics"]

[dependencies]
afl = "0.15"
arbitrary = { version = "1", features = ["derive"] }
ethnum = { path = ".." }
num = "0.4"
